tabapp/views/urls.py
# -*- coding: utf-8 -*-

from datetime import datetime
from flask import Blueprint, render_template, request, g, current_app, abort
from tabapp.models import db, Url
from tabapp.extensions.security import permisssion_required
import hashlib

urls_bp = Blueprint('urls_bp', __name__, subdomain='backyard')


@urls_bp.route('/', methods=['GET', 'POST'])
@permisssion_required(['normal'])
def index():
    if request.method == 'POST':
        long_url = request.form['long_url']
        if not long_url[:4] == 'http':
            long_url = 'http://{}'.format(long_url)
        m = hashlib.sha256()
        m.update(datetime.now().isoformat().encode())
        m.update(long_url.encode())
        url = Url()
        url.long_url = long_url
        url.uuid = m.hexdigest()[:5]
        db.session.add(url)
        db.session.commit()
    urls = Url.query.all()
    context = {
        'urls': urls,
    }
    return render_template('urls/list.html', **context)


@urls_bp.route('/<int:url_id>/')
@permisssion_required(['normal'])
def one(url_id):
    url = Url.query.get(url_id)
    if not url:
        return abort(404)
    context = {}
    return render_template('urls/url.html', **context)

tabapp/models/delivery_slip.py
# -*- coding: utf-8 -*-

from sqlalchemy.sql.expression import func
from datetime import date
from sqlalchemy.orm import relationship, backref
from sqlalchemy_utils import aggregated
from tabapp.models import db, DeliverySlipLine
import calendar
import sqlalchemy


def generate_no(context):
    today = date.today()
    month_range = calendar.monthrange(today.year, today.month)
    first_day = date(today.year, today.month, 1)
    last_day = date(today.year, today.month, month_range[1])
    idx = DeliverySlip.query.filter(DeliverySlip.delivery_date >= first_day,
        DeliverySlip.delivery_date <= last_day).count()
    return 'BD{}{:02d}{:03d}'.format(today.year, today.month, idx + 1)


class DeliverySlip(db.Model):
    __tablename__ = 'delivery_slip'
    id = db.Column(db.Integer, db.Sequence('core_seq_general'), primary_key=True)
    created = db.Column(db.DateTime, nullable=False, default=func.now())
    version = db.Column(db.DateTime, nullable=False, default=func.now(), onupdate=func.now())
    enabled = db.Column(db.Boolean, nullable=False, default=True)
    retailer_id = db.Column(db.Integer, db.ForeignKey('retailer.id'), nullable=False)
    retailer = relationship('Retailer')
    delivery_date = db.Column(db.Date, nullable=False, default=date.today)
    no = db.Column(db.String, nullable=False, default=generate_no)

    @aggregated('lines', db.Column(db.Numeric))
    def excl_tax_price(self):
        return sqlalchemy.func.sum(DeliverySlipLine.excl_tax_price)

    @aggregated('lines', db.Column(db.Numeric))
    def tax_price(self):
        return sqlalchemy.func.sum(DeliverySlipLine.tax_price)

    @aggregated('lines', db.Column(db.Numeric))
    def incl_tax_price(self):
        return sqlalchemy.func.sum(DeliverySlipLine.incl_tax_price)

tabapp/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms import widgets
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField, QuerySelectField
from wtforms.fields.html5 import DecimalField
from wtforms.validators import DataRequired, NumberRange, Email
from flask_babel import lazy_gettext
from tabapp.models import Role, Locale


class MultiCheckboxField(QuerySelectMultipleField):
    """
    A multiple-select, except displays a list of checkboxes.

    Iterating the field will produce subfields, allowing custom rendering of
    the enclosed checkbox fields.
    """
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class RetailerForm(Form):
    name = TextField(lazy_gettext('Name'), validators=[DataRequired()])
    code = TextField(lazy_gettext('Code'), validators=[DataRequired()])
    fees_proportion = DecimalField(lazy_gettext('Fees'), validators=[DataRequired(), NumberRange(0, 100)])
    address = TextField(lazy_gettext('Address'))
    zip = TextField(lazy_gettext('Zip'))
    city = TextField(lazy_gettext('City'))
    country = TextField(lazy_gettext('Country'))


class ContactForm(Form):
    firstname = TextField(lazy_gettext('Firstname'), validators=[DataRequired()])
    lastname = TextField(lazy_gettext('Lastname'), validators=[DataRequired()])
    email = TextField(lazy_gettext('Email'), validators=[DataRequired(), Email()])
    phone = TextField(lazy_gettext('Phone'))
    lang = QuerySelectField(label=lazy_gettext('Language'), get_label=lambda obj: obj.label, query_factory=lambda: Locale.query.filter(Locale.type=='lang'), allow_blank=True)
    tz = QuerySelectField(label=lazy_gettext('Timezone'), get_label=lambda obj: obj.label, query_factory=lambda: Locale.query.filter(Locale.type=='tz'), allow_blank=True)
    roles = MultiCheckboxField(label=lazy_gettext('Roles'), get_label=lambda obj: obj.name, query_factory=lambda: Role.query.filter())


class CredentialsForm(Form):
    username = TextField(lazy_gettext('Username'), validators=[DataRequired()])
    password = PasswordField(lazy_gettext('Password'), validators=[DataRequired()])


class RoleForm(Form):
    key = TextField(lazy_gettext('Key'), validators=[DataRequired()])
    name = TextField(lazy_gettext('Name'), validators=[DataRequired()])
    roles = MultiCheckboxField(get_label=lambda obj: obj.name)

tabapp/views/admin.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template
from tabapp.extensions.security import permisssion_required

admin_bp = Blueprint('admin_bp', __name__, subdomain='backyard')


@admin_bp.route('/')
@permisssion_required(['admin'])
def index():
    return render_template('admin/index.html')

tabapp/views/hooks.py
# -*- coding: utf-8 -*-

from flask import Blueprint, request, g, current_app, abort, jsonify, make_response
from flask_babel import gettext as _
from flask_cors import cross_origin
from tabapp.extensions.security import csrf
from tabapp.models import db, Product, Lead, ProductOrder
import tabapp.utils
import decimal

hooks_bp = Blueprint('hooks_bp', __name__, subdomain='hooks')


@csrf.exempt
@tabapp.utils.shopify_webhook
@hooks_bp.route('/products/', methods=['POST'])
def products():
    if not g.config['SYNC_ACTIVE']:
        return ''
    topic = request.headers.get('X-Shopify-Topic')
    product_id = request.headers.get('X-Shopify-Product-Id')
    data = request.get_json()
    callbacks = {
        'products/create': ProductAction.add,
        'products/update': ProductAction.update,
        'products/delete': ProductAction.delete,
    }
    callbacks[topic](product_id, data)
    return 'ok'


@csrf.exempt
@tabapp.utils.shopify_webhook
@hooks_bp.route('/product_orders/', methods=['POST'])
def product_orders():
    if not g.config['SYNC_ACTIVE']:
        return ''
    topic = request.headers.get('X-Shopify-Topic')
    product_order_id = request.headers.get('X-Shopify-Order-Id')
    data = request.get_json()
    callbacks = {
        'orders/paid': ProductOrderAction.upsert,
        'orders/updated': ProductOrderAction.upsert,
        'orders/delete': ProductOrderAction.delete,
        'orders/cancelled': ProductOrderAction.delete,
    }
    callbacks[topic](product_order_id, data)
    return 'ok'


@csrf.exempt
@hooks_bp.route('/subscribe/', methods=['POST'])
@cross_origin(origins=['http://www.tammyandbenjamin.com', 'http://tabdev.myshopify.com/'])
def subscribe():
    try:
        token = request.form['b_1c3be4482a6a53fea9c9c2e39_423d8800d8']
        if token:
            raise ValueError()
    except (KeyError, ValueError):
        abort(404)
    lead_email = request.form['lead_email']
    lead = Lead()
    lead.email = lead_email
    db.session.add(lead)
    db.session.commit()
    content = jsonify(success=_('Your email was successfully registered'))
    response = make_response(content)
    response.headers['Access-Control-Allow-Origin'] = request.headers['Origin']
    return response


class ProductAction(object):
    @staticmethod
    def add(product_id, data):
        tags = data.get('tags', '').split(', ')
        product = Product()
        product.remote_id = data.get('id')
        product.remote_variant_id = data.get('variants')[0].get('id')
        product.title = data.get('title')
        product.quantity = data.get('variants')[0].get('inventory_quantity')
        product.unit_price = data.get('variants')[0].get('price')
        if data.get('images'):
            product.image = data.get('images')[0].get('src')
        product.is_wholesale = 'WHOLESALE' in tags
        db.session.add(product)
        db.session.commit()
        current_app.logger.info('Product {} added.'.format(product.id))


    @staticmethod
    def update(product_id, data):
        tags = row.get('tags', '').split(', ')
        product = Product.query.filter(Product.remote_id == data.get('id')).first()
        if not product:
            return True
        product.title = data.get('title')
        product.quantity = data.get('variants')[0].get('inventory_quantity')
        product.unit_price = data.get('variants')[0].get('price')
        if data.get('images'):
            product.image = data.get('images')[0].get('src')
        product.is_wholesale = 'WHOLESALE' in tags
        db.session.commit()
        current_app.logger.info('Product {} updated.'.format(product.id))


    @staticmethod
    def delete(product_id, data):
        product = Product.query.filter(Product.remote_id == data.get('id')).first()
        if not product:
            return True
        db.session.delete(product)
        db.session.commit()


class ProductOrderAction(object):
    @staticmethod
    def upsert(product_order_id, data):
        product_order = ProductOrder.query.filter(ProductOrder.remote_id == product_order_id).first()
        if not product_order:
            product_order = ProductOrder()
            product_order.remote_id = product_order_id
            shipping_address = data.get('shipping_address')
            product_order.name = data.get('name')
            product_order.shipping_country = shipping_address['country_code'] if shipping_address else 'FR'
            product_order.subtotal_price = decimal.Decimal(data.get('subtotal_price', '0'))
            product_order.total_tax = decimal.Decimal(data.get('total_tax', '0'))
            product_order.total_price = decimal.Decimal(data.get('total_price', '0'))
            product_order.financial_status = data.get('financial_status')
            db.session.add(product_order)
        fields = [
            'id',
            'kind',
            'status',
            'amount',
            'created_at',
        ]
        resource = 'orders/{}/transactions'.format(product_order.remote_id)
        params = '?page={{page}}&limit={{limit}}&fields={fields}'.format(**{
            'fields': ','.join(fields),
        })
        transactions = tabapp.utils.list_from_resource(resource, params, key='transactions', page=1)
        if not transactions:
            return True
        transaction_ids = []
        paid_price = 0
        refunded_price = 0
        product_order.date = min([transaction.get('created_at') for transaction in transactions])
        for transaction in transactions:
            if not transaction.get('status') == 'success':
                continue
            if transaction.get('kind') in ['authorization', 'void']:
                continue
            transaction_ids.append(transaction.get('id'))
            if transaction.get('kind') in ['capture', 'sale']:
                paid_price += decimal.Decimal(transaction.get('amount'))
            if transaction.get('kind') in ['refund']:
                refunded_price += decimal.Decimal(transaction.get('amount'))
        product_order.transaction_ids = transaction_ids
        product_order.paid_price = paid_price
        product_order.refunded_price = refunded_price
        db.session.commit()
        current_app.logger.info('Product order {} upsert.'.format(product_order.id))


    @staticmethod
    def delete(product_order_id, data):
        product_order = ProductOrder.query.filter(ProductOrder.remote_id == product_order_id).first()
        if not product_order:
            return True
        db.session.delete(product_order)
        db.session.commit()

tabapp/views/login.py
# -*- coding: utf-8 -*-

from flask import Blueprint, request, render_template, g, redirect, url_for, flash, current_app, session
from flask_login import login_required, logout_user, login_user
from flask_babel import gettext as _
from flask_principal import Identity, AnonymousIdentity, identity_changed
from tabapp.models import Contact

login_bp = Blueprint('login_bp', __name__, subdomain='backyard')


@login_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    username = request.form.get('username')
    password = request.form.get('password')
    contact = Contact.query.filter(Contact.username == username).first()
    if not contact or contact.password != password:
        flash(_('Unknown user'), 'error')
        return render_template('login.html')
    login_user(contact)
    identity_changed.send(current_app._get_current_object(), identity=Identity(contact.id))
    return redirect(request.args.get('next') or url_for('index'))


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    for key in ('identity.name', 'identity.auth_type'):
        session.pop(key, None)
    identity_changed.send(current_app._get_current_object(), identity=AnonymousIdentity())
    return redirect(url_for('main_bp.index'))

tabapp/views/orders.py
# -*- coding: utf-8 -*-

from datetime import date
from dateutil.relativedelta import relativedelta
from flask import Blueprint, request, render_template
from tabapp.utils import list_from_resource, process_orders
from tabapp.extensions.security import permisssion_required
import math

orders_bp = Blueprint('orders_bp', __name__, subdomain='backyard')

@orders_bp.route('/', defaults={'page': 1})
@orders_bp.route('/<int:page>')
@permisssion_required(['normal'])
def index(page):
    default_lbound = date.today() - relativedelta(months=1)
    default_ubound = date.today()
    date_lbound = request.args.get('date_lbound', default_lbound)
    date_ubound = request.args.get('date_ubound', default_ubound)
    fields = [
        'name',
        'created_at',
        'customer',
        'tags',
        'line_items',
        'taxes_included',
        'tax_lines',
        'total_discounts',
    ]
    resource = 'orders'
    params = '?financial_status=paid&page={{page}}&fields={fields}{date_lbound}{date_ubound}'.format(**{
            'fields': ','.join(fields),
            'date_lbound': '&updated_at_min={}'.format(date_lbound) if date_lbound else '',
            'date_ubound': '&updated_at_max={}'.format(date_ubound) if date_ubound else '',
        })
    max_page = math.ceil(list_from_resource(resource, params, count = True) / 50)
    orders = list_from_resource(resource, params, page)
    orders = process_orders(orders)
    context = {
        'page': page,
        'date_lbound': date_lbound,
        'date_ubound': date_ubound,
        'max_page': max_page,
        'orders': orders,
    }
    return render_template('orders.html', **context)

tabapp/views/products.py
# -*- coding: utf-8 -*-

from flask import Blueprint, request, render_template,\
    jsonify, g, current_app, redirect, url_for, abort
from flask_login import login_required
from flask_babel import format_date, format_currency
from tabapp.models import db, Product, ProductCost
from datetime import date
from tabapp.extensions.security import permisssion_required
import tabapp.utils


products_bp = Blueprint('products_bp', __name__, subdomain='backyard')


@products_bp.route('/')
@permisssion_required(['normal'])
def index():
    page = int(request.args.get('page', 1))
    products = Product.query.paginate(page)
    products_retailers = {}
    for product in products.items:
        product_retailers = products_retailers.get(product.id, {})
        for stock in product.stocks:
            retailer_id = stock.retailer.id
            retailer_url = url_for('retailers_bp.retailer', retailer_id=retailer_id)
            retailer_link = '<a href="{}">{}</a>'.format(retailer_url, stock.retailer.name)
            product_retailers[retailer_id] = retailer_link
        products_retailers[product.id] = product_retailers
    context = {
        'products': products.items,
        'products_retailers': products_retailers,
        'page': products.page,
        'max_page': products.pages,
    }
    return render_template('products/list.html', **context)


@products_bp.route('/sync', methods=['POST'])
@permisssion_required(['normal'])
def sync():
    Product.sync_from_remote()
    if tabapp.utils.request_wants_json():
        return jsonify(success='Products sync.')
    return redirect(url_for('products_bp.index'))


@products_bp.route('/<int:product_id>/costs', methods=['GET', 'POST'])
@permisssion_required(['normal'])
def costs(product_id):
    if request.method == 'POST':
        product_cost = tabapp.utils.current_product_cost(product_id)
        if product_cost:
            product_cost.end_date = date.today()
        product_cost = ProductCost()
        product_cost.product_id = product_id
        product_cost.value = request.form.get('product_cost')
        product_cost.start_date = date.today()
        db.session.add(product_cost)
        db.session.commit()
        return jsonify(result=True)
    product = Product.query.get(product_id)
    if not product:
        return abort(404)
    costs = []
    for product_cost in product.costs:
        costs.append({
            'date': format_date(product_cost.start_date),
            'value': format_currency(product_cost.value, 'EUR'),
        })
    return jsonify(costs=costs)

tabapp/templates/base.html
<!doctype html>
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
        <title>TAMMY & BENJAMIN - Backyard</title>
        <style>
            body { padding-top: 50px; }
        </style>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand">TAMMY & BENJAMIN</a>
                </div>
                {% if g.current_user.is_authenticated() %}
                    <div class="navbar-right">
                        <a class="navbar-brand" href="{{ url_for('users_bp.account') }}"><small>{{ '%s %s.'|format(g.current_user.firstname, g.current_user.lastname[0:1]) }}</small></a>
                        <a class="navbar-brand" href="{{ url_for('login_bp.logout') }}">{{ _('Logout') }}</a>
                    </div>
                {% endif %}
            </div>
        </div>
        {% block page %}{% endblock page %}
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.5/waypoints.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.5/shortcuts/infinite-scroll/waypoints-infinite.min.js"></script>
        {% block script %}{% endblock script %}
    </body>
</html>

tabapp/templates/index.html
{% extends 'layout.html' %}

{% block content %}{% endblock content %}

tabapp/templates/layout.html
{% extends 'base.html' %}

{% block page %}
    <br />
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul class="nav nav-pills nav-stacked">
                    {% set tabs = [
                        ['orders', 'orders_bp.index', _('Orders')],
                        ['products', 'products_bp.index', _('Products')],
                        ['retailers', 'retailers_bp.index', _('Retailers')],
                        ['urls', 'urls_bp.index', _('Urls')],
                        ['admin', 'admin_bp.index', _('Admin')],
                    ] %}
                    {% for key, endpoint, label in tabs %}
                        {% if can_access(endpoint) %}
                            <li{% if main_tab ==  key %} class="active"{% endif %}><a href="{{ url_for(endpoint) }}">{{ label }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-10">
                {% with errors = get_flashed_messages(category_filter=["error"]) %}
                    {% if errors %}
                        {% for message in errors %}
                            <div class="alert alert-danger" role="alert">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock content %}
            </div>
        </div>
    </div>
{% endblock page %}

tabapp/templates/login.html
{% extends 'base.html' %}

{% block page %}
    <div style="width: 500px; margin: 10px auto;">
        {% with errors = get_flashed_messages(category_filter=["error"]) %}
            {% if errors %}
                {% for message in errors %}
                    <div class="alert alert-danger" role="alert">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <h1>{{ _('Who are you ?') }}</h1>
        <form name="login" method="POST" class="form-horizontal" role="form">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" placeholder="{{ _('Enter email') }}">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" placeholder="{{ _('Password') }}">
            </div>
            <button type="submit" class="btn btn-default">{{ _('Submit') }}</button>
        </form>
    </div>
{% endblock page %}

tabapp/templates/orders.html
{% extends 'layout.html' %}

{% set main_tab = 'orders' %}

{% block content %}
    <h1>{{ _('Sales') }}</h1>
    <a href="/orders/add">{{ _('Add order') }}</a>
    <form id="filters" class="form-inline" role="form" action="/orders/">
        <div class="form-group">
            <label for="date_lbound">{{ _('From') }}</label>
            <input type="date" class="form-control" name="date_lbound" value="{{ date_lbound }}" style="width: 160px;" />
        </div>
        <div class="form-group">
            <label for="date_ubound">{{ _('to') }}</label>
            <input type="date" class="form-control" name="date_ubound" value="{{ date_ubound }}" style="width: 160px;" />
        </div>
        <button class="btn btn-small">{{ _('Filter') }}</button>
    </form>
    <table id="sales" class="table table-condensed">
        <thead>
            <tr>
                <th>Order no.</th>
                <th>{{ _('Firstname') }}</th>
                <th>{{ _('Lastname') }}</th>
                <th>{{ _('Email') }}</th>
                <th>{{ _('Products') }}</th>
                <th style="white-space: nowrap;">{{ _('excl. VAT') }}</th>
                <th style="white-space: nowrap;">{{ _('excl. VAT discount') }}</th>
                <th style="white-space: nowrap;">{{ _('Cost') }}</th>
                <th style="white-space: nowrap;">{{ _('Profit') }}</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.order_no }}</td>
                    <td>{{ order.customer_firstname }}</td>
                    <td>{{ order.customer_lastname }}</td>
                    <td>{{ order.customer_email }}</td>
                    <td>{{ order.products | join(', ') }}</td>
                    <td style="white-space: nowrap; text-align: right;">{{ order.excluding_taxes_amount|currency }}</td>
                    <td style="white-space: nowrap; text-align: right;">{{ order.discount_amount|currency }}</td>
                    <td style="white-space: nowrap; text-align: right;">{{ order.cost_amount|currency }}</td>
                    <td style="white-space: nowrap; text-align: right;">{{ order.benefits|currency }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <ul id="pager" class="pagination">
        <li{% if page == 1 %} class="disabled"{% endif %}><a href="/orders/{{ page - 1 }}">&laquo;</a></li>
        {% for i in range(0, max_page) %}
            {% set real_i = i + 1 %}
            <li{% if page == real_i %} class="active"{% endif %}><a href="/orders/{{ real_i }}">{{ real_i }}</a></li>
        {% endfor %}
        <li{% if page == max_page %} class="disabled"{% endif %}><a href="/orders/{{ page + 1 }}">&raquo;</a></li>
    </ul>
{% endblock content %}

{% block script %}
    <script>
        (function($) {
            $('#pager').on('click', 'a', function(e) {
                var self = $(this);
                self.attr('href', self.attr('href') + window.location.search);
            });
        })(jQuery);
    </script>
{% endblock script %}

tabapp/templates/supplies.html
<html>
    <head>
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
        <title>TAMMY & BENJAMIN - Supplies</title>
        <style>
            table thead th { border: 0 !important; text-align: center; }
            table tbody td { font-family: verdana; font-size: 12px; text-align: center; }
        </style>
    </head>
    <body>
        <div style="text-align: center"><img src="http://cdn.shopify.com/s/files/1/0343/0553/t/5/assets/logo.png?7945"></div>
        <div style="padding: 40px 0 0 0; width:600px; height: 100px; margin: auto;">
            <div class="bg-danger pull-left" style="width: 150px; margin: 5px 0; text-align: center;">{{ _('Out of stock') }}</div>
            <form id="product_filter_form" class="form-inline pull-right" role="form">
                <div class="form-group">
                    <label class="sr-only" for="product_filter">{{ _('Filter products') }}</label>
                    <input type="search" class="form-control" id="product_filter" placeholder="{{ _('Filter products') }}">
                </div>
            </form>
            <table class="table table-bordered table table-hover table table-condensed">
                <thead>
                    <tr>
                        <th>{{ _('Product') }}</th>
                    <tr>
                </thead>
                <tbody id="products">
                    {% for product in products %}
                        <tr{% if product.quantity == 0 %} class="danger"{% endif %}>
                            <td>{{ product.title }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script>
            $(document).ready(function() {
                $('#product_filter_form').on('submit', function(e) {
                    e.preventDefault();
                });
                $('#product_filter').on('keyup', function(e) {
                    var self = $(this),
                        q = self.val(),
                        re = new RegExp(q, 'i');
                    $('#products tr').each(function() {
                        var row = $(this),
                            product_name = row.find('td').html();
                        row.hide();
                        if (re.test(product_name)) {
                            row.show();
                        }
                    });
                });
            });
        </script>
    </body>
</html>